# 03b - femsainfancias-missingcities_proximityresult-check

This notebook __loads the result of running proximity analysis for San Cristobal de las Casas and Ixtapa__ 

Note: Those cities are not included in INEGI's metropolis 2020, not in database. So it was necessary to create/calculate the following:
* __area of interest__ (metro_gdf_2020 > _femsainfancias_missingcities_metrogdf2020_)
* __hexgrid__ (hexgrid_{res}_city_2020 > _femsainfancias_missingcities_hexgrid_{res}_)
* __nodes__ (nodes_osmnx_23_point > _femsainfancias_missingcities_nodes_)
* __edges__ (edges_osmnx_23_line > _femsainfancias_missingcities_edges_)
* __edges_elevation__ (edges_elevation_23_line > _femsainfancias_missingcities_edgeselevation_)
* __edges_speed__ (edges_speed_23_line > _femsainfancias_missingcities_edgesspeed_)
* __pop data__ (pobcenso_inegi_20_mzaageb_hex > _femsainfancias_missingcities_censoageb_hex_)

## Import libraries

In [1]:
import os
import sys

import pandas as pd
import geopandas as gpd
import osmnx as ox
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

module_path = os.path.abspath(os.path.join('../../../'))
if module_path not in sys.path:
    sys.path.append(module_path)
    import aup

## Checking results

In [2]:
city = 'San Cristobal'

In [4]:
# Nodes proximity
proxnodes_schema = 'projects_research'
proxnodes_table = 'femsainfancias_missingcities_proxnode'

query = f"SELECT * FROM {proxnodes_schema}.{proxnodes_table} WHERE \"city\" LIKE \'{city}\'"
proxnodes_gdf = aup.gdf_from_query(query, geometry_col='geometry')
proxnodes_gdf = proxnodes_gdf.set_crs("EPSG:4326")

# Show
print(proxnodes_gdf.shape)
proxnodes_gdf.head(1)

(11799, 35)

,osmid,denue_preescolar,denue_primaria,denue_secundaria,clues_primer_nivel,denue_guarderias,denue_dif,denue_supermercado,denue_abarrotes,denue_carnicerias,...,sip_cancha,sip_unidad_deportiva,sip_espacio_publico,denue_parque_natural,denue_cines,denue_museos,x,y,geometry,city
0,280081838,84.323597,84.323597,95.261398,52.415106,154.155705,153.278292,156.070318,67.918919,91.6138,...,200.235612,None,84.323597,232.237482,164.737353,177.992964,-92.711953,16.689179,POINT (-92.71195 16.68918),San Cristobal

In [5]:
# hexs proximity
proxhexs_schema = 'projects_research'
proxhexs_table = 'femsainfancias_missingcities_proxhex'

query = f"SELECT * FROM {proxhexs_schema}.{proxhexs_table} WHERE \"city\" LIKE \'{city}\'"
proxhexs_gdf = aup.gdf_from_query(query, geometry_col='geometry')
proxhexs_gdf = proxhexs_gdf.set_crs("EPSG:4326")

# Show
print(proxhexs_gdf.shape)
proxhexs_gdf.head(1)

(1066, 48)

,hex_id,res,geometry,max_escuelas,max_preescolar,max_primaria,max_secundaria,max_servicios comunitarios,max_salud,max_guarderías,...,idx_sum,pobtot,pobfem,pobmas,p_0a14,p_15a24,p_25a59,p_60ymas,dens_pob_ha,city
0,886d23b169fffff,8,"POLYGON ((-92.68489 16.78370, -92.68050 16.786...",103.04351,8.348399,9.304488,103.04351,125.863549,7.270417,125.863549,...,9.314161,2115.8186,1168.0729,947.74554,771.79541,420.88945,772.75008,150.38344,26.971643,San Cristobal

In [9]:
city = 'Zihuatanejo'

In [10]:
# Nodes proximity
proxnodes_schema = 'projects_research'
proxnodes_table = 'femsainfancias_missingcities_proxnode'

query = f"SELECT * FROM {proxnodes_schema}.{proxnodes_table} WHERE \"city\" LIKE \'{city}\'"
proxnodes_gdf = aup.gdf_from_query(query, geometry_col='geometry')
proxnodes_gdf = proxnodes_gdf.set_crs("EPSG:4326")

# Show
print(proxnodes_gdf.shape)
proxnodes_gdf.head(1)

(9474, 35)

,osmid,denue_preescolar,denue_primaria,denue_secundaria,clues_primer_nivel,denue_guarderias,denue_dif,denue_supermercado,denue_abarrotes,denue_carnicerias,...,sip_cancha,sip_unidad_deportiva,sip_espacio_publico,denue_parque_natural,denue_cines,denue_museos,x,y,geometry,city
0,295506951,11.747864,35.008533,33.807103,6.987394,11.747864,12.334645,111.786241,3.154996,31.483427,...,23.897874,36.039633,8.62938,27.450205,5.008957,128.681379,-101.599217,17.658804,POINT (-101.59922 17.65880),Zihuatanejo

In [11]:
# hexs proximity
proxhexs_schema = 'projects_research'
proxhexs_table = 'femsainfancias_missingcities_proxhex'

query = f"SELECT * FROM {proxhexs_schema}.{proxhexs_table} WHERE \"city\" LIKE \'{city}\'"
proxhexs_gdf = aup.gdf_from_query(query, geometry_col='geometry')
proxhexs_gdf = proxhexs_gdf.set_crs("EPSG:4326")

# Show
print(proxhexs_gdf.shape)
proxhexs_gdf.head(1)

(810, 48)

,hex_id,res,geometry,max_escuelas,max_preescolar,max_primaria,max_secundaria,max_servicios comunitarios,max_salud,max_guarderías,...,idx_sum,pobtot,pobfem,pobmas,p_0a14,p_15a24,p_25a59,p_60ymas,dens_pob_ha,city
0,8849a2ade9fffff,8,"POLYGON ((-101.59660 17.64554, -101.59215 17.6...",50.184112,30.060643,50.184112,48.982682,30.548038,24.10513,30.060643,...,8.968631,213.16591,105.11491,108.05105,16.148935,10.86383,49.621284,31.123402,2.500754,Zihuatanejo

In [12]:
proxhexs_gdf.columns

Index(['hex_id', 'res', 'geometry', 'max_escuelas', 'max_preescolar',
       'max_primaria', 'max_secundaria', 'max_servicios comunitarios',
       'max_salud', 'max_guarderías', 'max_asistencia social', 'max_comercio',
       'max_alimentos', 'max_personal', 'max_farmacias', 'max_hogar',
       'max_complementarios', 'max_entretenimiento', 'max_social',
       'max_actividad física', 'max_cultural', 'idx_preescolar',
       'idx_primaria', 'idx_secundaria', 'idx_salud', 'idx_guarderías',
       'idx_asistencia social', 'idx_alimentos', 'idx_personal',
       'idx_farmacias', 'idx_hogar', 'idx_complementarios', 'idx_social',
       'idx_actividad física', 'idx_cultural', 'mean_time', 'median_time',
       'max_time', 'idx_sum', 'pobtot', 'pobfem', 'pobmas', 'p_0a14',
       'p_15a24', 'p_25a59', 'p_60ymas', 'dens_pob_ha', 'city'],
      dtype='object')