In [1]:
accesibilidad_urbana = '../../'

In [2]:
import geopandas as gpd
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

import os
import sys
module_path = os.path.abspath(os.path.join(accesibilidad_urbana))
if module_path not in sys.path:
    sys.path.append(module_path)
    import aup

In [13]:
# Load cities (municipalities)
metro_schema = 'metropolis'
metro_table = 'metro_gdf_2020'
metro_query = f"SELECT city FROM {metro_schema}.{metro_table}"
metro_gdf = aup.df_from_query(metro_query)
# Format
metro_gdf.drop_duplicates(inplace=True)
metro_gdf.reset_index(inplace=True,drop=True)
# Show
print(metro_gdf.shape)
print(len(list(metro_gdf.city.unique())))
metro_gdf.head(10)

(71, 1)
71

             city
0  Aguascalientes
1        Ensenada
2        Mexicali
3         Tijuana
4          La Paz
5       Los Cabos
6        Campeche
7          Laguna
8        Monclova
9  Piedras Negras

In [25]:
# Load hexs 2010
hex_schema = 'hexgrid'
hex_table = 'hexgrid_8_city'
hex_query = f"SELECT metropolis FROM {hex_schema}.{hex_table}"
hex_df = aup.df_from_query(hex_query)
# Format
hex_df.drop_duplicates(inplace=True)
hex_df.reset_index(inplace=True,drop=True)
# Register
for city in list(hex_df.metropolis.unique()):
    if city in list(metro_gdf.city.unique()):
        idx = metro_gdf.city==city
        metro_gdf.loc[idx,'hex8_2010'] = 1
    else:
        print(f"City {city} not in metro_gdf_2020.")

# Show
print(hex_df.shape)
hex_df.head(2)

City Tecoman not in metro_gdf_2020.
City Parral not in metro_gdf_2020.
City Moroleon not in metro_gdf_2020.
City San Francisco not in metro_gdf_2020.
City Tula not in metro_gdf_2020.
City Ocotlan not in metro_gdf_2020.
City Tianguistenco not in metro_gdf_2020.
City Tehuantepec not in metro_gdf_2020.
City Teziutlan not in metro_gdf_2020.
City Rio Verde not in metro_gdf_2020.
City Acayucan not in metro_gdf_2020.
(74, 1)

       metropolis
0  Aguascalientes
1        Ensenada

In [26]:
# Load hexs 2020
hex_schema = 'hexgrid'
hex_table = 'hexgrid_8_city_2020'
hex_query = f"SELECT city FROM {hex_schema}.{hex_table}"
hex_df = aup.df_from_query(hex_query)
# Format
hex_df.drop_duplicates(inplace=True)
hex_df.reset_index(inplace=True,drop=True)
# Register
for city in list(hex_df.city.unique()):
    if city in list(metro_gdf.city.unique()):
        idx = metro_gdf.city==city
        metro_gdf.loc[idx,'hex8_2020'] = 1
    else:
        print(f"City {city} not in metro_gdf_2020.")
# Show
print(hex_df.shape)
hex_df.head(2)

(71, 1)

           city
0  Villahermosa
1     Matamoros

In [27]:
metro_gdf.head(35)

              city  hex8_2010  hex8_2020
0   Aguascalientes        1.0        1.0
1         Ensenada        1.0        1.0
2         Mexicali        1.0        1.0
3          Tijuana        1.0        1.0
4           La Paz        1.0        1.0
5        Los Cabos        NaN        1.0
6         Campeche        1.0        1.0
7           Laguna        1.0        1.0
8         Monclova        1.0        1.0
9   Piedras Negras        1.0        1.0
10        Saltillo        1.0        1.0
11          Colima        1.0        1.0
12       Tapachula        1.0        1.0
13          Tuxtla        1.0        1.0
14       Chihuahua        1.0        1.0
15        Delicias        1.0        1.0
16          Juarez        1.0        1.0
17            CDMX        NaN        1.0
18            ZMVM        1.0        1.0
19         Durango        1.0        1.0
20          Celaya        1.0        1.0
21      Guanajuato        1.0        1.0
22            Leon        1.0        1.0
23        Irapuato        NaN        1.0
24        Acapulco        1.0        1.0
25    Chilpancingo        1.0        1.0
26         Pachuca        1.0        1.0
27      Tulancingo        1.0        1.0
28     Guadalajara        1.0        1.0
29        Vallarta        1.0        1.0
30          Piedad        1.0        1.0
31          Toluca        1.0        1.0
32         Morelia        1.0        1.0
33          Zamora        1.0        1.0
34         Uruapan        NaN        1.0

In [24]:
metro_gdf.tail(36)

              city  hex8_2010  hex8_2020
35         Cuautla        1.0        1.0
36      Cuernavaca        1.0        1.0
37           Tepic        1.0        1.0
38       Monterrey        1.0        1.0
39          Oaxaca        1.0        1.0
40          Puebla        1.0        1.0
41      San Martin        NaN        1.0
42        Tehuacan        1.0        1.0
43       Queretaro        1.0        1.0
44          Cancun        1.0        1.0
45        Chetumal        1.0        1.0
46           Playa        NaN        1.0
47             SLP        1.0        1.0
48        Culiacan        1.0        1.0
49      Los Mochis        NaN        1.0
50        Mazatlan        1.0        1.0
51         Guaymas        1.0        1.0
52  Ciudad Obregon        NaN        1.0
53      Hermosillo        1.0        1.0
54         Nogales        1.0        1.0
55    Villahermosa        1.0        1.0
56        Victoria        1.0        1.0
57       Matamoros        1.0        1.0
58    Nuevo Laredo        1.0        1.0
59         Reynosa        1.0        1.0
60         Tampico        1.0        1.0
61        Tlaxcala        1.0        1.0
62   Coatzacoalcos        1.0        1.0
63         Cordoba        1.0        1.0
64      Minatitlan        1.0        1.0
65         Orizaba        1.0        1.0
66       Poza Rica        1.0        1.0
67        Veracruz        1.0        1.0
68          Xalapa        1.0        1.0
69          Merida        1.0        1.0
70       Zacatecas        1.0        1.0