In [1]:
import os
import sys

import pandas as pd
import geopandas as gpd
import numpy as np

import matplotlib.pyplot as plt
from matplotlib import colors
import seaborn as sns

from pandas.api.types import CategoricalDtype

import warnings
warnings.simplefilter(action='ignore', category=FutureWarning)

module_path = os.path.abspath(os.path.join('../../../'))
if module_path not in sys.path:
    sys.path.append(module_path)
    import aup

/usr/local/python/lib/python3.10/site-packages/osmnx/utils.py:192: UserWarning: The `utils.config` function is deprecated and will be removed in a future release. Instead, use the `settings` module directly to configure a global setting's value. For example, `ox.settings.log_console=True`.
  warnings.warn(

In [3]:
# Analysis name
index_analysis = 'ndwi'

# Analysed raster data from local directory:
tmp_dir = f'../../../data/processed/tmp_{index_analysis}/'

In [7]:
#Load data
city = 'presa_laboca'
r = 12
laboca_complete_dataset = pd.read_csv(tmp_dir+'local_save/'+f'{city}_{index_analysis}_HexRes{r}_.csv')
laboca_complete_dataset = laboca_complete_dataset.drop(columns=['Unnamed: 0'])
laboca_complete_dataset

                  hex_id  res      ndwi  month  year          city
0        8c48a2c48393bff   12  0.636882      1  2016  presa_laboca
1        8c48a2c484f31ff   12 -0.614095      1  2016  presa_laboca
2        8c48a2116c565ff   12  0.850477      1  2016  presa_laboca
3        8c48a2c4ba8a7ff   12 -0.813694      1  2016  presa_laboca
4        8c48a21169a65ff   12 -0.615940      1  2016  presa_laboca
...                  ...  ...       ...    ...   ...           ...
3052975  8c48a21168b41ff   12 -0.423991     12  2022  presa_laboca
3052976  8c48a2c48ad13ff   12 -0.193714     12  2022  presa_laboca
3052977  8c48a21161321ff   12 -0.236016     12  2022  presa_laboca
3052978  8c48a2c4841c3ff   12 -0.471327     12  2022  presa_laboca
3052979  8c48a2c48ab11ff   12 -0.228394     12  2022  presa_laboca

[3052980 rows x 6 columns]

In [8]:
#Load data
city = 'presa_laboca'
r = 12
laboca_complete_dataset_2023 = pd.read_csv(tmp_dir+'local_save/'+f'{city}_{index_analysis}_HexRes{r}_v0.csv')
laboca_complete_dataset_2023 = laboca_complete_dataset_2023.drop(columns=['Unnamed: 0'])
laboca_complete_dataset_2023

                  hex_id  res      ndwi  month  year          city
0        8c48a2c4841d7ff   12 -0.755518      1  2016  presa_laboca
1        8c48a2c4bae0dff   12 -0.597222      1  2016  presa_laboca
2        8c48a2c4b8ac1ff   12  0.954590      1  2016  presa_laboca
3        8c48a2c4bb109ff   12  0.726562      1  2016  presa_laboca
4        8c48a21160401ff   12 -0.332410      1  2016  presa_laboca
...                  ...  ...       ...    ...   ...           ...
3343735  8c48a21168353ff   12 -0.370578      8  2023  presa_laboca
3343736  8c48a2c4b0169ff   12 -0.358100      8  2023  presa_laboca
3343737  8c48a211685ddff   12 -0.362576      8  2023  presa_laboca
3343738  8c48a2c4b82a7ff   12  0.124037      8  2023  presa_laboca
3343739  8c48a2c495833ff   12  0.131246      8  2023  presa_laboca

[3343740 rows x 6 columns]

In [33]:
laboca_2022 = laboca_complete_dataset.loc[laboca_complete_dataset.year == 2022]
laboca_b_2022 = laboca_complete_dataset_2023.loc[laboca_complete_dataset_2023.year == 2023]

In [31]:
analysis_bydate = pd.DataFrame()  

for month in laboca_2022.month.unique():
    presa_gdf_month = laboca_2022.loc[(laboca_2022.month == month)]
    
    temp = presa_gdf_month.ndwi.mean()
    print(temp)

-0.25881366693201113
-0.19841378734325016
-0.1834249134179821
-0.20932862885137823
-0.2314379294305838
-0.2524110230881843
-0.28050779082207494
-0.20760660799465935
-0.2158269766349386
-0.2240468031268075
-0.23226690048527385
-0.197905288418427

In [34]:
analysis_bydate = pd.DataFrame()  

for month in laboca_b_2022.month.unique():
    presa_gdf_month = laboca_b_2022.loc[(laboca_b_2022.month == month)]
    
    temp = presa_gdf_month.ndwi.mean()
    print(temp)

-0.17003960229053414
-0.13034495297666177
-0.16182204933549732
-0.18298617603534634
-0.20415029840097357
-0.2253144294901862
-0.24707324732954253
-0.21904793303744136